/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cargo;

import static cargo.B.jTable1;
import static cargo.searchproductclient.paymentmethod;
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SADIQ
 */
public class ClientPayment extends javax.swing.JFrame {

    /**
     * Creates new form ClientPayment
     */
    public ClientPayment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtbill = new javax.swing.JTextArea();
        billbtn = new javax.swing.JButton();
        pdf = new javax.swing.JButton();
        txttotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PrdName", "qtn", "Price", "total", "Payment Method"
            }
        ));
        jScrollPane1.setViewportView(table);

        txtbill.setColumns(20);
        txtbill.setRows(5);
        jScrollPane2.setViewportView(txtbill);

        billbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        billbtn.setText("Confirm Payment");
        billbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billbtnActionPerformed(evt);
            }
        });

        pdf.setText("pdf");
        pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdfActionPerformed(evt);
            }
        });

        jLabel1.setText("Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(pdf)
                                .addGap(141, 141, 141))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(billbtn)
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(pdf)
                .addGap(65, 65, 65)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(billbtn))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        searchproductclient bk = new searchproductclient();
        bk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed
 Connection connection;
    ResultSet rs;
     PreparedStatement pst;
    private void billbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billbtnActionPerformed
        // TODO add your handling code here:
       

        bill();

     

    }//GEN-LAST:event_billbtnActionPerformed


    private void pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdfActionPerformed
     
        String path = "";
        
        JFileChooser j = new JFileChooser();
     j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
     int x = j.showSaveDialog(this);
     if(x==JFileChooser.APPROVE_OPTION){
     
     path = j.getSelectedFile().getPath();
     }
     
     
     
     Document doc = new Document();
     
        try {
            PdfWriter.getInstance(doc,new FileOutputStream(path+"paymentslip.pdf"));
            
            doc.open();
            PdfPTable tb1 = new PdfPTable(5);
            
            
            tb1.addCell("Purchased Product");
            tb1.addCell("Quantity");
            tb1.addCell("Price");
            tb1.addCell("Total");
            tb1.addCell("Payment Method");
            
            
            for(int i =0 ; i <table.getRowCount(); i++){
            
            
            String prdn = table.getValueAt(i, 0).toString();
            String qtn = table.getValueAt(i, 1).toString();
            String pr = table.getValueAt(i, 2).toString();
            String tot = table.getValueAt(i, 3).toString();
            String paym = table.getValueAt(i, 4).toString();
            
            tb1.addCell(prdn);
            tb1.addCell(qtn);
            tb1.addCell(pr);
            tb1.addCell(tot);
            tb1.addCell(paym);
            
            }
            
            doc.add(tb1);
            
            JOptionPane.showMessageDialog(null, "Downloded pdf file",  "ALERT MESSAGE", JOptionPane.WARNING_MESSAGE);
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ClientPayment.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(ClientPayment.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        doc.close();
    }//GEN-LAST:event_pdfActionPerformed
    
    
    
    
     public void bill(){
    
   
    
    
    DefaultTableModel model = new DefaultTableModel();
    model = (DefaultTableModel)table.getModel();
    DateTimeFormatter time = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss"); 
    LocalDateTime n = LocalDateTime.now();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");  
   LocalDateTime now = LocalDateTime.now();
     //System.out.println(dtf.format(now));
   
       //System.out.println(time.format(n)); 
       
        int sum = 0;
        for(int i=0 ;i<table.getRowCount();i++){

            sum = sum + Integer.parseInt(table.getValueAt(i, 3).toString());

        }
       String sus = Integer.toString(sum);
       
    
    txtbill.setText(txtbill.getText() + "******************************\n");
     txtbill.setText(txtbill.getText() + "*        BILL                *\n");
     txtbill.setText(txtbill.getText() + "******************************\n");
     txtbill.setText(txtbill.getText() + "Payment Time"+ "\t" +dtf.format(now)+ "\t"+ "\n");
      txtbill.setText(txtbill.getText() + "Product" + "\t" + "Product Price" + "\t" + "Quantity" + "\t" + "PaymentSystem"+ "\n");
      
      for(int i = 0;i < model.getRowCount(); i++)
      {
      
      String pname = (String)model.getValueAt(i, 0);
      String price = (String)model.getValueAt(i, 2);
      String quantity = (String)model.getValueAt(i, 1);
      String payment = (String)model.getValueAt(i, 4);
      
      
      txtbill.setText(txtbill.getText() + pname + "\t" + price + "\t" + quantity + "\t" + payment +  "\n");
      
      }
    
    txtbill.setText(txtbill.getText() + "\n");
     txtbill.setText(txtbill.getText() + "\n");
     txtbill.setText(txtbill.getText() + "\t" + "\t" + "Total Price :" + sus + "\n");
   
       txttotal.setText(sus);
      
     txtbill.setText(txtbill.getText() + "******************************\n");
    
     
       try{
         
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=Cargos;selectMethod=cursor", "sa", "123456");

                pst = connection.prepareStatement("INSERT INTO Payment (PaymentSystem,TotalPrice,PaidTime) VALUES('"+searchproductclient.paymentmethod+"','"+sus+"','"+time.format(n)+"')");

                rs = pst.executeQuery();

    
    
    
    
    
    
    
    
    
    
    
    }catch(Exception e){}
     
   
     
     
     

     
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    public static void AddRowTJTable(Object[] dataRow){
    
    DefaultTableModel model = (DefaultTableModel)table.getModel();
    model.addRow(dataRow);
    
    
    
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientPayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton billbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton pdf;
    public static javax.swing.JTable table;
    private javax.swing.JTextArea txtbill;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
