/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cargo;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SADIQ
 */
public class ClientsOrder extends javax.swing.JFrame {

    /**
     * Creates new form ClientsOrder
     */
    public ClientsOrder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtprodcut = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtqtn = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        ad = new javax.swing.JButton();
        showtbl = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtamnt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtbill = new javax.swing.JTextArea();
        billbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        paymenttype = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtpay = new javax.swing.JTextField();
        txtprctid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtclientid = new javax.swing.JTextField();
        txtadress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        dltbtn = new javax.swing.JButton();
        txtavalabeqtn = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtremainingqtn = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Search Product");

        txtprodcut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprodcutActionPerformed(evt);
            }
        });
        txtprodcut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtprodcutKeyPressed(evt);
            }
        });

        jLabel2.setText("Quantity");

        txtqtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqtnActionPerformed(evt);
            }
        });

        jLabel6.setText("Product Price");

        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });

        ad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ad.setText("Add");
        ad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adActionPerformed(evt);
            }
        });

        showtbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        showtbl.setText("Display");
        showtbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showtblActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PrdName", "qtn", "Price", "total", "Payment Method"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setText("Total Price");

        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });

        jLabel3.setText("Total");

        txtbill.setColumns(20);
        txtbill.setRows(5);
        jScrollPane2.setViewportView(txtbill);

        billbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        billbtn.setText("Confirm Payment");
        billbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billbtnActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        paymenttype.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        paymenttype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Select Payment---", "Cash", "bKash", " " }));

        jLabel5.setText("Payment");

        jLabel7.setText("Productid");

        jLabel8.setText("ClientID");

        jLabel9.setText("Client Address");

        dltbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dltbtn.setText("Delete");
        dltbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dltbtnActionPerformed(evt);
            }
        });

        jLabel10.setText("available quantity");

        jLabel11.setText("Remaining qtn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel10)))
                                    .addComponent(ad))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtprodcut, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                            .addComponent(txtqtn)
                                            .addComponent(txtprice, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                            .addComponent(txtamnt)
                                            .addComponent(txtavalabeqtn))
                                        .addGap(73, 73, 73)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(paymenttype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel11))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtpay, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                                    .addComponent(txttotal, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                                    .addComponent(txtremainingqtn)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(showtbl)
                                        .addGap(30, 30, 30)
                                        .addComponent(dltbtn))))
                            .addComponent(jButton1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(billbtn)
                                .addGap(36, 36, 36)))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtclientid, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtprctid, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtadress, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel8)
                    .addComponent(txtclientid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtprctid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtprodcut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtqtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(paymenttype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtamnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtavalabeqtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(showtbl)
                                    .addComponent(ad, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dltbtn))
                                .addGap(6, 6, 6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtpay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtremainingqtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtadress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(billbtn)
                        .addGap(6, 6, 6))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 Connection connection;
    ResultSet rs;
     PreparedStatement pst;
    private void txtprodcutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprodcutKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            String prdname = txtprodcut.getText();

            try{

                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=Cargos;selectMethod=cursor", "sa", "123456");

                pst = connection.prepareStatement("select * from Products,Clients where Description = '"+prdname+"'");

                rs = pst.executeQuery();

                if(rs.next() == false){
                    JOptionPane.showMessageDialog(this, "not found");

                }else{

                    String price = rs.getString("Price");
                    String prouctid = rs.getString("Productid");
                    String clientid = rs.getString("Clinetid");
                    String address = rs.getString("CAddress");
                    String availabequantity = rs.getString("Quantity");
                    
                    txtprice.setText(price);
                    txtprctid.setText(prouctid);
                    txtclientid.setText(clientid);
                    txtadress.setText(address);
                    txtavalabeqtn.setText(availabequantity);

                }
            }catch(Exception e){}

        }
    }//GEN-LAST:event_txtprodcutKeyPressed

    private void txtqtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtqtnActionPerformed

    private void adActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adActionPerformed
        String qtn = txtqtn.getText();
        String pr = txtprice.getText();
        int p = Integer.parseInt(pr);
        int qty = Integer.parseInt(qtn);
        int tol = qty * p;
        txtamnt.setText(String.valueOf(tol));
        if( paymenttype.getSelectedIndex()==1 || paymenttype.getSelectedIndex()==2 ){
        txtpay.setText(paymenttype.getSelectedItem().toString());
        
       
          try{
         
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=Cargos;selectMethod=cursor", "sa", "123456");

                pst = connection.prepareStatement("INSERT INTO Delivery (DAddress) VALUES('"+txtadress.getText()+"')");

                rs = pst.executeQuery();

    
    
    
    
    
    
    
    
    
    
    
    }catch(Exception e){}
        
        
        
        
        
        
        
        
        
        
        }
    }//GEN-LAST:event_adActionPerformed

    private void showtblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showtblActionPerformed
        
        display();
        decrement();
    

        

    }//GEN-LAST:event_showtblActionPerformed
public void display(){

    DefaultTableModel model = new DefaultTableModel();
        model  = (DefaultTableModel)jTable1.getModel();

        model.addRow(new Object[]{

            txtprodcut.getText(),
            txtqtn.getText(),
            txtprice.getText(),
            txtamnt.getText(),
            txtpay.getText()
          
        });

        int sum = 0;
        for(int i=0 ;i<jTable1.getRowCount();i++){

            sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());

        }

        txttotal.setText(Integer.toString(sum));




    
    
    

}

public void decrement(){

 String qtn = txtqtn.getText();
 String av = txtavalabeqtn.getText();
        int qty = Integer.parseInt(qtn);
        int avi = Integer.parseInt(av);
        
        txtremainingqtn.setText(String.valueOf(avi-qty));
        
       
 
          try{
         
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=Cargos;selectMethod=cursor", "sa", "123456");

                pst = connection.prepareStatement("update Products set Quantity = '"+txtremainingqtn.getText()+"' where Productid= '"+txtprctid.getText()+"'");

                rs = pst.executeQuery();

    
    
    
    
    
    
    
    
    
    
    
    }catch(Exception e){}
       







}



    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceActionPerformed

    private void billbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billbtnActionPerformed
        // TODO add your handling code here:
        balance();

        bill();
        
        
        
          try{
         
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=Cargos;selectMethod=cursor", "sa", "123456");

                pst = connection.prepareStatement("INSERT INTO buy (Productid, Clinetid, Qtn) VALUES('"+txtprctid.getText()+"','"+txtclientid.getText()+"','"+txtqtn.getText()+"')");

                rs = pst.executeQuery();

    
    
    
    
    
    
    
    
    
    
    
    }catch(Exception e){}
        
        
    }//GEN-LAST:event_billbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        signin prd = new signin();
        prd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtprodcutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprodcutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprodcutActionPerformed

    private void dltbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dltbtnActionPerformed
        
        
          DefaultTableModel model = new DefaultTableModel();
        model  = (DefaultTableModel)jTable1.getModel();
        
        
        if(jTable1.getSelectedRowCount() == 1){
        
        model.removeRow(jTable1.getSelectedRow());
        
        
         }else{
          
            if(jTable1.getSelectedRowCount() == 0){
            
            JOptionPane.showMessageDialog(this, "Table is Empty.");
            
            }else{
            
            JOptionPane.showMessageDialog(this, "Select row to delete");
            }
            
        
        }
    }//GEN-LAST:event_dltbtnActionPerformed
  
    public void balance(){
    
    

    
    int total  = Integer.parseInt(txttotal.getText());
    //int pay = Integer.parseInt(txtpay.getText());
    //int bal = pay - total;
    //txtbal.setText(String.valueOf(bal));
    
    
    }
    public void bill(){
    
    String total = txttotal.getText();
    //String pay = txtpay.getText();
    //String bal = txtbal.getText();
    
    DefaultTableModel model = new DefaultTableModel();
    model = (DefaultTableModel)jTable1.getModel();
    DateTimeFormatter time = DateTimeFormatter.ofPattern("HH:mm:ss"); 
    LocalDateTime n = LocalDateTime.now();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");  
   LocalDateTime now = LocalDateTime.now();
     //System.out.println(dtf.format(now));
   
       System.out.println(time.format(n)); 
       
    
    txtbill.setText(txtbill.getText() + "******************************\n");
     txtbill.setText(txtbill.getText() + "*        BILL                *\n");
     txtbill.setText(txtbill.getText() + "******************************\n");
     txtbill.setText(txtbill.getText() + "Payment Time"+ "\t" +dtf.format(now)+ "\t"+ "\n");
      txtbill.setText(txtbill.getText() + "Product" + "\t" + "Product Price" + "\t" + "Quantity" + "\t" + "PaymentSystem"+ "\n");
      
      for(int i = 0;i < model.getRowCount(); i++)
      {
      
      String pname = (String)model.getValueAt(i, 0);
      String price = (String)model.getValueAt(i, 2);
      String quantity = (String)model.getValueAt(i, 1);
      String payment = (String)model.getValueAt(i, 4);
      
      
      txtbill.setText(txtbill.getText() + pname + "\t" + price + "\t" + quantity + "\t" + payment +  "\n");
      
      }
    
    txtbill.setText(txtbill.getText() + "\n");
     txtbill.setText(txtbill.getText() + "\n");
     txtbill.setText(txtbill.getText() + "\t" + "\t" + "Total Price :" + total + "\n");
   
   
    
     txtbill.setText(txtbill.getText() + "******************************\n");
    
   
     
     
     
     try{
         
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=Cargos;selectMethod=cursor", "sa", "123456");

                pst = connection.prepareStatement("INSERT INTO Payment (PaymentSystem,TotalPrice,PaidTime) VALUES('"+txtpay.getText()+"','"+total+"','"+time.format(n)+"')");

                rs = pst.executeQuery();

    
    
    
    
    
    
    
    
    
    
    
    }catch(Exception e){}
     
    }
    
    
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientsOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientsOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientsOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientsOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientsOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ad;
    private javax.swing.JButton billbtn;
    private javax.swing.JButton dltbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> paymenttype;
    private javax.swing.JButton showtbl;
    private javax.swing.JTextField txtadress;
    private javax.swing.JTextField txtamnt;
    private javax.swing.JTextField txtavalabeqtn;
    private javax.swing.JTextArea txtbill;
    private javax.swing.JTextField txtclientid;
    private javax.swing.JTextField txtpay;
    private javax.swing.JTextField txtprctid;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtprodcut;
    private javax.swing.JTextField txtqtn;
    private javax.swing.JTextField txtremainingqtn;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
