/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cargo;

import static cargo.A.jTextField1;
import static cargo.ClientPayment.table;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author SADIQ
 */
public class searchproductclient extends javax.swing.JFrame {

    /**
     * Creates new form searchproductclient
     */
    public searchproductclient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paymenttype = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        display = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtprdname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtqtn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtamnt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtavalabeqtn = new javax.swing.JTextField();
        paymenttype1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtpay = new javax.swing.JTextField();
        txtremainingqtn = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtprctid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtclientid = new javax.swing.JTextField();
        txtadress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        addcart = new javax.swing.JButton();
        txtsearch = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        paymenttype.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        paymenttype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Select Payment---", "Cash", "bKash", " " }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        display.setText("display product");
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductId", "ProductName", "Price"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Product Name");

        txtqtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqtnActionPerformed(evt);
            }
        });
        txtqtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtqtnKeyPressed(evt);
            }
        });

        jLabel2.setText("Quantity");

        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });

        jLabel6.setText("Product Price");

        jLabel3.setText("Total");

        jLabel10.setText("available quantity");

        paymenttype1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        paymenttype1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Select Payment---", "Cash", "bKash", " " }));
        paymenttype1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                paymenttype1KeyPressed(evt);
            }
        });

        jLabel5.setText("Payment");

        txtremainingqtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtremainingqtnActionPerformed(evt);
            }
        });

        jLabel11.setText("Remaining qtn");

        jLabel7.setText("Productid");

        jLabel8.setText("ClientID");

        jLabel9.setText("Client Address");

        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jButton1.setText("CART");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        addcart.setText("ADD TO CART");
        addcart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcartActionPerformed(evt);
            }
        });

        txtsearch.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        txtsearch.setForeground(new java.awt.Color(51, 51, 51));
        txtsearch.setText("Search Product....");
        txtsearch.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtsearchMouseClicked(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Log Out");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(display)
                        .addGap(31, 31, 31)
                        .addComponent(jButton1)
                        .addGap(36, 36, 36)
                        .addComponent(addcart)
                        .addGap(170, 170, 170))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtprdname, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(txtqtn))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtpay, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtremainingqtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtamnt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtavalabeqtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addComponent(jButton4))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(243, Short.MAX_VALUE)
                    .addComponent(paymenttype1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(77, 77, 77)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel9)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtclientid, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtprctid, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtadress, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtprdname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtqtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtpay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtamnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtavalabeqtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtremainingqtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(display)
                    .addComponent(add)
                    .addComponent(jButton1)
                    .addComponent(addcart))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(paymenttype1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(txtclientid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(txtprctid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtadress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))))
                    .addContainerGap(333, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static String availabeqtn;

public static String remainingqtn;

public static String paymentmethod;
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       int i = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        
        txtprdname.setText(model.getValueAt(i, 1).toString());

        txtprctid.setText(model.getValueAt(i, 0).toString());
        txtprice.setText(model.getValueAt(i, 2).toString());


    }//GEN-LAST:event_jTable1MouseClicked

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
   table_update();   
   clientid();
    }//GEN-LAST:event_displayActionPerformed

    private void txtqtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtqtnActionPerformed

    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
              
        
        available();
        decrement();
        buytble();
        payment();
        insert();
    
        
        
    }//GEN-LAST:event_addActionPerformed

    
    public void insert(){
    
          String qtn = txtqtn.getText();
        String pr = txtprice.getText();
        int p = Integer.parseInt(pr);
        int qty = Integer.parseInt(qtn);
        int tol = qty * p;
        
        
         
 //String av = txtavalabeqtn.getText();
  String av = availabeqtn;
        int avi = Integer.parseInt(av);
        
       int remaining = avi - qty;
        if(remaining>=0 && avi>=qty){
        txtamnt.setText(String.valueOf(tol));
        }
            if( paymenttype1.getSelectedIndex()==1 || paymenttype1.getSelectedIndex()==2 ){
        txtpay.setText(paymenttype1.getSelectedItem().toString());
        
        
        paymentmethod = txtpay.getText();
                System.err.println("Payment Method: "+paymentmethod);
       
          try{
         
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=Cargos;selectMethod=cursor", "sa", "123456");

                pst = connection.prepareStatement("INSERT INTO Delivery (DAddress) VALUES('"+txtadress.getText()+"')");

                rs = pst.executeQuery();

    
    
    
    
    
    
    
    
    
    
    
    }catch(Exception e){}
        
        
        
        
        
        
        
        
        
        
        }
    
    
    
    
    }
    
    public void payment(){
    
      DateTimeFormatter time = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss"); 
    LocalDateTime n = LocalDateTime.now();
        
     int sum = 0;
        for(int i=0 ;i<ClientPayment.table.getRowCount();i++){

            sum = sum + Integer.parseInt(ClientPayment.table.getValueAt(i, 3).toString());

        }
       String sus = Integer.toString(sum);
        System.out.println(sus);
    
        try{
         
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=Cargos;selectMethod=cursor", "sa", "123456");

                pst = connection.prepareStatement("INSERT INTO Payment (PaymentSystem,TotalPrice,PaidTime) VALUES('"+txtpay.getText()+"','"+sus+"','"+time.format(n)+"')");

                rs = pst.executeQuery();

    
    
    
    
    
    
    
    
    
    
    
    }catch(Exception e){}
    
    
    
    
    }
    
    public void buytble(){
    
    
         try{
         
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=Cargos;selectMethod=cursor", "sa", "123456");

                pst = connection.prepareStatement("INSERT INTO buy (Productid, Clinetid, Qtn) VALUES('"+txtprctid.getText()+"','"+txtclientid.getText()+"','"+txtqtn.getText()+"')");

                rs = pst.executeQuery();

    
    
    
    
    
    
    
    
    
    
    
    }catch(Exception e){}
    
    
    
    
    
    
    
    
    
    
    }
    
public void decrement(){

 String qtn = txtqtn.getText();
 String av = txtavalabeqtn.getText();
       int qty = Integer.parseInt(qtn);
       int avi = Integer.parseInt(availabeqtn);
       //System.err.println("avi:" + avi);
       
        //int avi = Integer.parseInt(av);
        
       int remaining = avi - qty;
        
      if(remaining>=0 && avi>=qty){
      
       //txtremainingqtn.setText(String.valueOf(remaining));
       remainingqtn = String.valueOf(remaining);
          System.err.println("Remaining: "+remainingqtn);
       try{
         
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=Cargos;selectMethod=cursor", "sa", "123456");

                pst = connection.prepareStatement("update Products set Quantity = '"+remainingqtn+"' where Productid= '"+txtprctid.getText()+"'");

                rs = pst.executeQuery();

    
    
    
    
    
    
    
    
    
    
    
    }catch(Exception e){
      // JOptionPane.showMessageDialog(null, e);
    
    }
        
        
 
         
      
      
      }else{
      JOptionPane.showMessageDialog(null, "Limit exceeded");
     
      //clear();
    
      //txtclientid.setText("");
      //txtadress.setText("");
      
      }
            
                 //JOptionPane.showMessageDialog(null, "Limit exceeded");
                 //this.dispose();
        
        
        
        
          
        
        
    
      
       
       
       
       







}


public void clear(){

  txtprdname.setText("");
      txtqtn.setText("");
      txtprice.setText("");
      txtamnt.setText("");
      //txtavalabeqtn.setText("");
      txtpay.setText("");
      txtremainingqtn.setText("");
      txtprctid.setText("");




}



    private void txtqtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtqtnKeyPressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txtqtnKeyPressed

    private void paymenttype1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paymenttype1KeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_paymenttype1KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   ClientPayment bk = new ClientPayment();
        bk.setVisible(true);
        //this.dispose();       
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addcartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcartActionPerformed
          
        
        
        ClientPayment.AddRowTJTable(new Object[]{
      
        
          txtprdname.getText(),
        txtqtn.getText(),
        txtprice.getText(),
        txtamnt.getText(),
        txtpay.getText()
        
        
        });
        clear();
    }//GEN-LAST:event_addcartActionPerformed

    private void txtsearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtsearchMouseClicked
        txtsearch.setText("");
    }//GEN-LAST:event_txtsearchMouseClicked

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
     
        String tf = txtsearch.getText();
        
        try {
            String query = "select Productid,Description,Price from Products where Description like '%"+tf+"%'";
            pst = connection.prepareStatement(query);
            rs = pst.executeQuery();
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
        }
        
        
        
    }//GEN-LAST:event_txtsearchKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        signin bk = new signin();
        bk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtremainingqtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtremainingqtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtremainingqtnActionPerformed
 public static String availabequantity;
    public void available(){
    
    
      try{
         
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=Cargos;selectMethod=cursor", "sa", "123456");

                pst = connection.prepareStatement("select * from Products where Productid = '"+txtprctid.getText()+"' ");

                rs = pst.executeQuery();

    
                if(rs.next() == false){
                    JOptionPane.showMessageDialog(this, "not found");

                }else{

               
                     availabequantity = rs.getString("Quantity");
                    
                   
                   // txtavalabeqtn.setText(availabequantity);
          
                }
    
    
   // availabeqtn = txtavalabeqtn.getText();
       availabeqtn = availabequantity;
          System.err.println("availble: "+availabeqtn);
    
    
    
    
    
    
    }catch(Exception e){}
        
        
    
    
    
    
    
    
    }

    
     
    
    
    
    
    
    Connection connection;
    ResultSet rs;
     PreparedStatement pst;
     
    
     public void table_update(){
         
         
          try{
    
    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=Cargos;selectMethod=cursor", "sa", "123456");
            

            Statement statement = connection.createStatement();
            
                   
             int c;
            
                   ResultSet resultSet = statement
                    .executeQuery("select * from Products");
                   ResultSetMetaData rss= resultSet.getMetaData();
            
            c=rss.getColumnCount();
            
             DefaultTableModel tbmodel = (DefaultTableModel)jTable1.getModel();
              tbmodel.setRowCount(0);
              while (resultSet.next()) {
             
        Vector v2 = new Vector();
              
        
                  
                 
                 
                  
                  
                    for(int a=1;a<=c;a++){
                        v2.add(resultSet.getString("Productid"));
                      
                      v2.add(resultSet.getString("Description"));
                   
                      v2.add(resultSet.getString("Price"));
                 
                  
                  
                  }
                   tbmodel.addRow(v2);
                   
                  
                  
    
                
                
                
            }
            
       
             
             
            
            
    }catch(Exception e){
    
       e.printStackTrace();
    
    
    }
     }
     
     
     
     
     
     
     public void clientid(){
         
        signin x = new signin();
         System.out.println("mail:  "+signin.mail);

    try{
           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=Cargos;selectMethod=cursor", "sa", "123456");

                pst = connection.prepareStatement("select Clinetid,CAddress from Clients where Mail = '"+signin.mail+"'  ");

             
              rs = pst.executeQuery();
              
              
               if(rs.next() == false){
           
               
               }else{
               
               
                   
               String pkid = rs.getString("Clinetid");
               txtclientid.setText(pkid);
                String ad = rs.getString("CAddress");
               txtadress.setText(ad);
               
               
               }
       
 
            
    
    }catch(Exception e){
      JOptionPane.showMessageDialog(null,e);
    
    
    } 
    





}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchproductclient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchproductclient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchproductclient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchproductclient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchproductclient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton addcart;
    private javax.swing.JButton display;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> paymenttype;
    private javax.swing.JComboBox<String> paymenttype1;
    private javax.swing.JTextField txtadress;
    public static javax.swing.JTextField txtamnt;
    private javax.swing.JTextField txtavalabeqtn;
    private javax.swing.JTextField txtclientid;
    public static javax.swing.JTextField txtpay;
    private javax.swing.JTextField txtprctid;
    public static javax.swing.JTextField txtprdname;
    public static javax.swing.JTextField txtprice;
    public static javax.swing.JTextField txtqtn;
    private javax.swing.JTextField txtremainingqtn;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
